version: "3.7"
services:
  app:
    command: yarn start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
